"""add page number to documents

Revision ID: 02c4407bd1ef
Revises: 11bb5474de83
Create Date: 2026-08-30 00:40:59.008046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c4407bd1ef'
down_revision: Union[str, Sequence[str], None] = '11bb5474de83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_page_number'), 'documents', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_page_number'), table_name='documents')
    op.drop_column('documents', 'page_number')
    # ### end Alembic commands ###
