"""add location to conversations

Revision ID: 50d595317c53
Revises: 02c4407bd1ef
Create Date: 2026-09-04 18:44:54.838284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d595317c53'
down_revision: Union[str, Sequence[str], None] = '02c4407bd1ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'longitude')
    op.drop_column('conversations', 'latitude')
    # ### end Alembic commands ###
