"""make email required

Revision ID: 79cdf5aacffd
Revises: cf49fc71bc55
Create Date: 2026-08-14 16:55:44.536047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cdf5aacffd'
down_revision: Union[str, Sequence[str], None] = 'cf49fc71bc55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Existing users with NULL email ko unique temporary email do
    op.execute("""
        UPDATE users
        SET email = 'user_' || id || '@temp.local'
        WHERE email IS NULL
    """)

    # Ab email ko required karo
    op.alter_column(
        'users',
        'email',
        existing_type=sa.VARCHAR(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
